# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

covid_psgs_w100:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.covid_split.covid_psgs_w100
  id_prefix: "covid:"
